# -*- coding: utf-8 -*-
"""HW2_Requests & Beautiful Soup.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uw90IaQt6DWLUUf81nK6h0FwcbSk0_-g
"""

# Connetced yourself Cloud Storage
from google.colab import drive
drive.mount('/content/gdrive/', force_remount=True)

import os
os.chdir("/content/gdrive/My Drive/11202_latia/")
os.listdir()

# 導入requests函式庫
import requests

# 從bs4套件中導入BeautifulSoup，用於解析HTML或XML文件。
from bs4 import BeautifulSoup

# 通過requests函式庫的get函數向"https://today.line.me/tw/v2/movie/chart/trending"發送了一個GET請求，並將回應儲存在response對象中。
url = 'https://today.line.me/tw/v2/movie/chart/trending'
response = requests.get(url=url)

# 設置回應的編碼方式為UTF-8。這是為了確保中文等非ASCII字符能夠正確解碼。
response.encoding = "utf-8"

# 使用BeautifulSoup將取得的HTML內容解析為soup物件，其中，response.text是HTTP回應的文本內容，"html.parser"是指定的HTML解析器。
soup = BeautifulSoup(response.text, 'html.parser')

#輸出內容
print(soup.prettify())

# 使用soup.find_all()方法搜尋div標籤且class為 detailListItem 的內容，回傳符合內容並成1個列表。
info_items = soup.find_all('div', 'detailListItem')

# 透過 for 迴圈及 find 方法取出每一部電影中的以下四個資訊
for item in info_items:
    ranking = item.find('div', 'detailListItem-ranking rankingBadge').div.text.strip()
    name = item.find('div', 'detailListItem-titles').h2.text.strip()
    english_name = item.find('div', 'detailListItem-titles').h3.text.strip()
    score = item.find('div', 'detailListItem-status').div.text.strip()

# 印出結果
    print('第{}名 : {}({})\n評分：{}'.format(ranking, name, english_name, score))

# 匯入csv模組
import csv

# 使用soup.find_all()方法搜尋div標籤且class為 detailListItem 的內容，回傳符合內容並成1個列表。
info_items = soup.find_all('div', 'detailListItem')

# 透過 with open 方法並將要建立的檔案名稱設為「0422-0428電影排名.csv」
with open('0422-0428電影排名.csv', 'w', encoding='utf-8', newline='') as csv_file:

    csv_writer = csv.writer(csv_file)
    csv_writer.writerow(['排名', '電影中文片名', '電影英文片名', '網友評分'])     # 寫入欄位名稱

# 透過 for 迴圈將每部電影的資料逐一寫入檔案中
    for item in info_items:
        ranking = item.find('div', 'detailListItem-ranking rankingBadge').div.text.strip()
        name = item.find('div', 'detailListItem-titles').h2.text.strip()
        english_name = item.find('div', 'detailListItem-titles').h3.text.strip()
        score = item.find('div', 'detailListItem-status').div.text.strip()

        csv_writer.writerow([ranking, name, english_name, score])